# fly.toml app configuration file generated for podfi on 2024-06-20T12:39:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'podfi'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  auto_stop_machines = false

[checks]
  [checks.api]
    port = 5000
    type = 'http'
    interval = '1m0s'
    timeout = '10s'
    grace_period = '10s'
    method = 'get'
    path = '/api'

[[vm]]
  size = 'shared-cpu-1x'
