# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          pnpm install
      - name: Store .env file
        run: |
          echo '${{ secrets.ENV }}' > .env
          echo '${{ secrets.ENV }}' > @podfi/webapp/.env
      - name: Build assets
        run: |
          pnpm run build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to staging
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
